// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVAD1WluWKCz3fM1VoXZd7u4FMy1FC-s',
    appId: '1:385961846021:web:cb9dc0d623f2afd78a436c',
    messagingSenderId: '385961846021',
    projectId: 'education-app-3f147',
    authDomain: 'education-app-3f147.firebaseapp.com',
    storageBucket: 'education-app-3f147.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4YFSlTH_1uNLAWZF7p5agSM_MRzgyISA',
    appId: '1:385961846021:android:8ba16d03d352e8498a436c',
    messagingSenderId: '385961846021',
    projectId: 'education-app-3f147',
    storageBucket: 'education-app-3f147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYDxDaKHcSUD4zW3hdkmNeN6rquFw04MM',
    appId: '1:385961846021:ios:382ef0cdbd2551248a436c',
    messagingSenderId: '385961846021',
    projectId: 'education-app-3f147',
    storageBucket: 'education-app-3f147.appspot.com',
    iosClientId: '385961846021-umc5bar0ho54lrvj1s6d12h32g3sfpl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEducationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYDxDaKHcSUD4zW3hdkmNeN6rquFw04MM',
    appId: '1:385961846021:ios:382ef0cdbd2551248a436c',
    messagingSenderId: '385961846021',
    projectId: 'education-app-3f147',
    storageBucket: 'education-app-3f147.appspot.com',
    iosClientId: '385961846021-umc5bar0ho54lrvj1s6d12h32g3sfpl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEducationApp',
  );
}
